### ISSUE TITLE
Add to Planned Enhancements in DG

### ISSUE THREAD

**Issue by Jaynon** [AY2425S1-CS2103T-F11-3/tp#307]
- [ ]  #290 - Text overflow for tag 
- [ ] #255 - Reminder Feature
- [ ] #251 - multiple doctors, same appointment in different time
- [ ] #249 - NRIC Checksum
- [ ] #228 - multiple appointments 
- [ ] #227 - variable appointment length
